# From project root, run docker compose up
version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  aic-api:
    build: .
    container_name: aic-api
    ports:
      - "8888:8888"
    depends_on:
      - redis
    env_file:
      - .env
    restart: always
    volumes:
    - ./monitoring:/app/monitoring

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - aic-api
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/nginx/key:/key
