// Code generated by hertz generator.

package main

import (
	"context"
	"flag"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/cloudwego/hertz/pkg/app/server"
	redisv8 "github.com/go-redis/redis/v8"
	"github.com/joho/godotenv"
	"github.com/sirupsen/logrus"
	"gitlab.com/aic/aic_api/biz/dal"
	"gitlab.com/aic/aic_api/biz/handler"
	"gitlab.com/aic/aic_api/biz/router/aic_api"
	"gitlab.com/aic/aic_api/consts"
	"gitlab.com/aic/aic_api/logs"
	"gitlab.com/aic/aic_api/monitoring"
)

type CustomClient struct {
	RedisClient *redisv8.Client
}

func (c *CustomClient) Get(ctx context.Context, key string) ([]byte, error) {
	val, err := c.RedisClient.Get(ctx, key).Result()
	if err != nil {
		return nil, err
	}
	return []byte(val), nil
}

func (c *CustomClient) Set(ctx context.Context, key string, val any, ttl time.Duration) error {
	err := c.RedisClient.Set(ctx, key, val, ttl).Err()
	// if there has been an error setting the value
	// handle the error
	if err != nil {
		logs.CtxError(ctx, "error setting value: %v", err)
		return err
	}
	return nil
}

func (c *CustomClient) Del(ctx context.Context, key string) error {
	err := c.RedisClient.Del(ctx, key).Err()
	// if there has been an error setting the value
	// handle the error
	if err != nil {
		logs.CtxError(ctx, "error setting value: %v", err)
		return err
	}
	return nil
}

var environment string

func main() {
	h := server.Default(
		server.WithHostPorts(getHostPort()),
	)
	logrus.Info("[main.go/main] Server is running on ", getHostPort())

	err := godotenv.Load(".env")
	if err != nil {
		logrus.Fatal("[main.go/main] Fatal error when retrieving env variables", err)
		os.Exit(1)
	}

	register(h)

	if err := dal.InitDB(isTestEnv()); err != nil {
		panic(err)
	}

	//Initialises log writer
	logWriter := monitoring.InitWriter()
	go logWriter.Run()

	// RedisAddr := os.Getenv("REDISADDR")
	// err = redis.NewRedis(RedisAddr)
	// if err != nil {
	// 	logrus.Fatal("Fatal error when initialising redis", err)
	// 	panic(err)
	// }

	// CustomClient := &CustomClient{}
	// CustomClient.RedisClient = redis.RedisClient

	// cacheConfig := &cache.Config{ // Configuration used to initialise cache
	// 	DefaultSoftTTL: consts.DefaultSoftTTL, // Global softTTL if one is not provided at the time of function call. (Refer to concepts and notes for more info)
	// 	DefaultHardTTL: consts.DefaultHardTTL, // Global hardTTL if one is not provided at the time of functon call. (Refer to concepts and notes for more info)
	// 	CacheConfig: service.Config{ // Cache configuration, this must be provided.
	// 		CacheProvider: constants.CustomCacheType, // Choose cache provider as CustomCacheType
	// 		CustomConfiguration: &service.CustomConfig{ // Custom configuration is required if CacheProvider is set to CustomConfiguration
	// 			Client: CustomClient, // Custom client that implements Get and Set
	// 		},
	// 	},
	// 	SkipCache: false,    // Global toggle on whether or not to skip cache. Useful for toggling between environments.
	// 	Version:   "v1.0.0", // Version number set. If there are any upgrades, this prevents breaking changes as old keys will not be re-used.
	// 	Env:       environment,
	// }

	// if err := cache.Init(cacheConfig); err != nil {
	// 	panic(err) // panic if caching fails to initialise
	// }

	h.Spin()

	// Create a channel to receive OS signals
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	// Start the server in a goroutine
	go func() {
		if err := h.Run(); err != nil {
			logrus.Error("Error running server:", err)
		}
	}()

	// Wait for termination signal
	<-stop

	logrus.Info("[main.go/main] Shutting down server...")

	// Create a deadline for the shutdown
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	// Attempt to gracefully shut down the server
	if err := h.Shutdown(ctx); err != nil {
		logrus.Error("[main.go/main] Server forced to shutdown:", err)
	}

	logrus.Info("[main.go/main] Server exiting")
}

// register registers all routers.
func register(r *server.Hertz) {
	logrus.Info("[main.go/register] registering routes")

	// Register routes generated by IDL
	aic_api.Register(r)

	// Register custom routes
	r.GET("/ping", handler.Ping)
}

func isTestEnv() bool {
	env := flag.String("env", "test", "Server environment")
	flag.Parse()

	if *env == "test" {
		environment = consts.TEST
		logrus.Info("[main.go/isTestEnv] environment set to test")
		return true
	} else if *env == "prod" {
		environment = consts.PROD
		logrus.Info("[main.go/isTestEnv] environment set to prod")
		return false
	} else {
		logrus.Info("[main.go/isTestEnv] invalid environment, defaulting to test environment")
	}
	environment = consts.TEST

	return true
}

func getHostPort() string {
	host := os.Getenv("SERVER_HOST")
	if host == "" {
		host = "0.0.0.0"
	}
	port := os.Getenv("SERVER_PORT")
	if port == "" {
		port = "8888"
	}
	return host + ":" + port
}
