// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	aic_api "gitlab.com/aic/aic_api/biz/model/aic_api"
)

// GetQuestionsQuery .
// @router /api/v:version/aic/questions/get [POST]
func GetQuestionsQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req aic_api.GetQuestionsRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(aic_api.GetQuestionsResponse)

	c.JSON(consts.StatusOK, resp)
}
