// Code generated by hertz generator.

package aic_api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _vversionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _cofMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signinqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signoutqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _meMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemyprofilequeryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _aicMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _profilesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _questionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getquestionsqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadquestionsqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmyprofilequeryMw() []app.HandlerFunc {
	// your code...
	return nil
}
